## Cleaning ttc_delays

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df_delays = pd.read_excel("ttc_delays.xlsx") #Reading the file

In [5]:
df_delays.head(10) #Showing the first 10 rows
df_delays.info() #Overview of the dataset
df_delays.describe() #Statistics for numerical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26467 entries, 0 to 26466
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       26467 non-null  datetime64[ns]
 1   Time       26467 non-null  object
 2   Day        26467 non-null  object
 3   Station    26467 non-null  object
 4   Code       26467 non-null  object
 5   Min Delay  26467 non-null  int64
 6   Min Gap    26467 non-null  int64
 7   Bound      16947 non-null  object
 8   Line       26423 non-null  object
 9   Vehicle    26467 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 2.0+ MB

                                Date     Min Delay       Min Gap       Vehicle
count                          26467  26467.000000  26467.000000  26467.000000
mean   2024-07-01 21:44:28.273699584      2.806287      4.110628   3224.485850
min              2024-01-01 00:00:00      0.000000      0.000000      0.000000
25%              2024-04-01 00:00:00      0.000000      0.000000      0.000000
50%              2024-07-02 00:00:00      0.000000      0.000000   5120.000000
75%              2024-10-03 00:00:00      4.000000      8.000000   5606.000000
max              2024-12-31 00:00:00    716.000000    719.000000   9546.000000
std                              NaN     10.090619     10.857043   2747.754357

In [6]:
#Rename columns:
df_delays = df_delays.rename(columns={
    "Min Delay": "Min_Delay",
    "Min Gap": "Min_Gap"
})

#Look for missing values:
df_delays.isnull().sum()

# Fill empty cells (9520) in Bound with 'Unknown'
df_delays["Bound"] = df_delays["Bound"].fillna("Unknown")

#Drop 44 rows with missing 'Line' value
df_delays = df_delays.dropna(subset=["Line"])

#Remove duplicates
df_delays = df_delays.drop_duplicates()

#Extract month, day and day of the week from date

df_delays["Month"] = df_delays["Date"].dt.month
df_delays["Day"] = df_delays["Date"].dt.day
df_delays["Weekday"] = df_delays["Date"].dt.day_name()

In [7]:
df_delays.head(10) #Showing the first 10 rows

,Date,Time,Day,Station,Code,Min_Delay,Min_Gap,Bound,Line,Vehicle,Month,Weekday
0,2024-01-01,02:00,1,SHEPPARD STATION,MUI,0,0,N,YU,5491,1,Monday
1,2024-01-01,02:00,1,DUNDAS STATION,MUIS,0,0,N,YU,0,1,Monday
2,2024-01-01,02:08,1,DUNDAS STATION,MUPAA,4,10,N,YU,6051,1,Monday
3,2024-01-01,02:13,1,KENNEDY BD STATION,PUTDN,10,16,E,BD,5284,1,Monday
4,2024-01-01,02:22,1,BLOOR STATION,MUPAA,4,10,N,YU,5986,1,Monday
5,2024-01-01,02:25,1,ST CLAIR STATION,MUPAA,3,9,N,YU,6051,1,Monday
6,2024-01-01,02:25,1,BLOOR STATION,MUIRS,0,0,S,YU,0,1,Monday
7,2024-01-01,02:27,1,WOODBINE STATION,EUDO,7,13,E,BD,5077,1,Monday
8,2024-01-01,02:28,1,FINCH STATION,MUIRS,0,0,S,YU,5561,1,Monday
9,2024-01-01,02:30,1,DAVISVILLE STATION,MUI,13,19,N,YU,6051,1,Monday

In [8]:
df_delays.to_csv("cleaned_ttc_delays.csv", index=False)

## Cleaning weather

In [9]:
df_weather = pd.read_csv("weather.csv") #Reading the file

In [10]:
df_weather.head(10)

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-79.4,43.67,TORONTO CITY,6158355,2024-01-01,2024,1,1,NaN,-0.7,...,NaN,NaN,0.1,NaN,2.0,NaN,NaN,M,NaN,M
1,-79.4,43.67,TORONTO CITY,6158355,2024-01-02,2024,1,2,NaN,1.5,...,NaN,NaN,0.0,NaN,0.0,NaN,NaN,M,NaN,M
2,-79.4,43.67,TORONTO CITY,6158355,2024-01-03,2024,1,3,NaN,3.1,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
3,-79.4,43.67,TORONTO CITY,6158355,2024-01-04,2024,1,4,NaN,1.8,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
4,-79.4,43.67,TORONTO CITY,6158355,2024-01-05,2024,1,5,NaN,0.4,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
5,-79.4,43.67,TORONTO CITY,6158355,2024-01-06,2024,1,6,NaN,2.1,...,NaN,NaN,5.0,NaN,NaN,NaN,NaN,M,NaN,M
6,-79.4,43.67,TORONTO CITY,6158355,2024-01-07,2024,1,7,NaN,0.7,...,NaN,NaN,0.1,NaN,5.0,NaN,NaN,M,NaN,M
7,-79.4,43.67,TORONTO CITY,6158355,2024-01-08,2024,1,8,NaN,3.7,...,NaN,NaN,0.0,NaN,4.0,NaN,NaN,M,NaN,M
8,-79.4,43.67,TORONTO CITY,6158355,2024-01-09,2024,1,9,NaN,7.0,...,NaN,NaN,31.2,NaN,1.0,NaN,NaN,M,NaN,M
9,-79.4,43.67,TORONTO CITY,6158355,2024-01-10,2024,1,10,NaN,6.7,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M

In [11]:
#Rename columns (remove slashes and spaces):
df_weather.columns = df_weather.columns.str.strip().str.replace(" ", "_")
df_weather.columns = (df_weather.columns.str.strip().str.replace(r"[ /]+", "_", regex=True))
df_weather.columns = (
    df_weather.columns
    .str.strip()
    .str.replace(r"[ /()]+", "_", regex=True)
)
#Look for missing values:
df_weather.isnull().sum()

#Remove duplicates
df_weather = df_weather.drop_duplicates()

#Assign the day of the week after converting Date_Time to dt
df_weather["Date_Time"] = pd.to_datetime(df_weather["Date_Time"], errors="coerce")
df_weather["Weekday"] = df_weather["Date_Time"].dt.day_name()

In [12]:
#Look for missing values:
df_weather.isnull().sum()

Longitude__x_                  0
Latitude__y_                   0
Station_Name                   0
Climate_ID                     0
Date_Time                      0
Year                           0
Month                          0
Day                            0
Data_Quality                 366
Max_Temp__°C_                  3
Max_Temp_Flag                363
Min_Temp__°C_                  3
Min_Temp_Flag                363
Mean_Temp__°C_                 3
Mean_Temp_Flag               363
Heat_Deg_Days__°C_             3
Heat_Deg_Days_Flag           363
Cool_Deg_Days__°C_             3
Cool_Deg_Days_Flag           363
Total_Rain__mm_              366
Total_Rain_Flag              366
Total_Snow__cm_              366
Total_Snow_Flag              366
Total_Precip__mm_              3
Total_Precip_Flag            363
Snow_on_Grnd__cm_            317
Snow_on_Grnd_Flag            366
Dir_of_Max_Gust__10s_deg_    366
Dir_of_Max_Gust_Flag           0
Spd_of_Max_Gust__km_h_       366
Spd_of_Max_Gust_Flag           0
Weekday                        0
dtype: int64

In [13]:
df_weather.info() #Overview of the dataset
df_weather.describe() #Statistics for numerical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Longitude__x_              366 non-null    float64
 1   Latitude__y_               366 non-null    float64
 2   Station_Name               366 non-null    object
 3   Climate_ID                 366 non-null    int64
 4   Date_Time                  366 non-null    datetime64[ns]
 5   Year                       366 non-null    int64
 6   Month                      366 non-null    int64
 7   Day                        366 non-null    int64
 8   Data_Quality               0 non-null      float64
 9   Max_Temp__°C_              363 non-null    float64
 10  Max_Temp_Flag              3 non-null      object
 11  Min_Temp__°C_              363 non-null    float64
 12  Min_Temp_Flag              3 non-null      object
 13  Mean_Temp__°C_             363 non-null    float64
 14  Mean_Temp_Flag             3 non-null      object
 15  Heat_Deg_Days__°C_         363 non-null    float64
 16  Heat_Deg_Days_Flag         3 non-null      object
 17  Cool_Deg_Days__°C_         363 non-null    float64
 18  Cool_Deg_Days_Flag         3 non-null      object
 19  Total_Rain__mm_            0 non-null      float64
 20  Total_Rain_Flag            0 non-null      float64
 21  Total_Snow__cm_            0 non-null      float64
 22  Total_Snow_Flag            0 non-null      float64
 23  Total_Precip__mm_          363 non-null    float64
 24  Total_Precip_Flag          3 non-null      object
 25  Snow_on_Grnd__cm_          49 non-null     float64
 26  Snow_on_Grnd_Flag          0 non-null      float64
 27  Dir_of_Max_Gust__10s_deg_  0 non-null      float64
 28  Dir_of_Max_Gust_Flag       366 non-null    object
 29  Spd_of_Max_Gust__km_h_     0 non-null      float64
 30  Spd_of_Max_Gust_Flag       366 non-null    object
 31  Weekday                    366 non-null    object
dtypes: datetime64[ns](1), float64(17), int64(4), object(10)
memory usage: 91.6+ KB

,Longitude__x_,Latitude__y_,Climate_ID,Date_Time,Year,Month,Day,Data_Quality,Max_Temp__°C_,Min_Temp__°C_,...,Cool_Deg_Days__°C_,Total_Rain__mm_,Total_Rain_Flag,Total_Snow__cm_,Total_Snow_Flag,Total_Precip__mm_,Snow_on_Grnd__cm_,Snow_on_Grnd_Flag,Dir_of_Max_Gust__10s_deg_,Spd_of_Max_Gust__km_h_
count,3.660000e+02,3.660000e+02,366.0,366,366.0,366.000000,366.000000,0.0,363.000000,363.000000,...,363.000000,0.0,0.0,0.0,0.0,363.000000,49.000000,0.0,0.0,0.0
mean,-7.940000e+01,4.367000e+01,6158355.0,2024-07-01 12:00:00.000000256,2024.0,6.513661,15.756831,NaN,14.976584,7.562259,...,1.174105,NaN,NaN,NaN,NaN,2.560882,2.040816,NaN,NaN,NaN
min,-7.940000e+01,4.367000e+01,6158355.0,2024-01-01 00:00:00,2024.0,1.000000,1.000000,NaN,-7.400000,-16.300000,...,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,-7.940000e+01,4.367000e+01,6158355.0,2024-04-01 06:00:00,2024.0,4.000000,8.000000,NaN,7.000000,1.200000,...,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
50%,-7.940000e+01,4.367000e+01,6158355.0,2024-07-01 12:00:00,2024.0,7.000000,16.000000,NaN,15.400000,6.800000,...,0.000000,NaN,NaN,NaN,NaN,0.000000,1.000000,NaN,NaN,NaN
75%,-7.940000e+01,4.367000e+01,6158355.0,2024-09-30 18:00:00,2024.0,9.750000,23.000000,NaN,23.750000,15.450000,...,1.500000,NaN,NaN,NaN,NaN,1.300000,3.000000,NaN,NaN,NaN
max,-7.940000e+01,4.367000e+01,6158355.0,2024-12-31 00:00:00,2024.0,12.000000,31.000000,NaN,33.100000,24.200000,...,9.900000,NaN,NaN,NaN,NaN,83.600000,10.000000,NaN,NaN,NaN
std,4.838305e-13,6.403639e-14,0.0,NaN,0.0,3.455958,8.823592,NaN,9.866223,8.711454,...,2.164554,NaN,NaN,NaN,NaN,7.729788,2.414877,NaN,NaN,NaN

In [14]:
df_weather.to_csv("cleaned_weather.csv", index=False)

In [15]:
## Cleaning routes

In [16]:
df_routes = pd.read_csv("routes.txt")

df_routes = df_routes.drop_duplicates()

df_routes.columns = (
    df_routes.columns
    .str.strip()
    .str.replace(r"[ \-()/]+", "_", regex=True)
    .str.replace(r"_+", "_", regex=True)
)

missing_values = df_routes.isnull().sum()
print(missing_values)

route_id              0
agency_id             0
route_short_name      0
route_long_name       0
route_desc          230
route_type            0
route_url           230
route_color           0
route_text_color      0
dtype: int64

In [17]:
df_routes.to_excel("cleaned_routes.xlsx", index=False)

## Creating one Excel file with Routes, Weather and Delays sheets

In [18]:
with pd.ExcelWriter("ttc_project_data.xlsx", engine="openpyxl") as writer:
    df_delays.to_excel(writer, sheet_name="Delays", index=False)
    df_weather.to_excel(writer, sheet_name="Weather", index=False)
    df_routes.to_excel(writer, sheet_name="Routes", index=False)